<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('236', '/uploads/allimg/200507/1305444411-0.jpg');
$maNum = 1;
$myaddons[$maNum] = array('237', '/uploads/allimg/200507/1305443961-1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('238', '/uploads/allimg/200507/1305442250-2.jpg');
$maNum = 3;
$myaddons[$maNum] = array('239', '/uploads/allimg/200507/1305443L6-3.jpg');
$maNum = 4;
$myaddons[$maNum] = array('240', '/uploads/allimg/200507/1305442632-4.jpg');
$maNum = 5;
$myaddons[$maNum] = array('241', '/uploads/allimg/200507/1305444R5-5.jpg');
$maNum = 6;
