<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('1102', '/uploads/allimg/200615/021S92204-0.jpg');
$maNum = 1;
$myaddons[$maNum] = array('1103', '/uploads/allimg/200615/021S94118-1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('1104', '/uploads/allimg/200615/021Sa596-2.jpg');
$maNum = 3;
$myaddons[$maNum] = array('1105', '/uploads/allimg/200615/021S922M-3.jpg');
$maNum = 4;
$myaddons[$maNum] = array('1106', '/uploads/allimg/200615/021S95b5-4.jpg');
$maNum = 5;
$myaddons[$maNum] = array('1107', '/uploads/allimg/200615/021S95593-5.jpg');
$maNum = 6;
