<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('2228', '/uploads/allimg/200508/14021T915-0.jpg');
$maNum = 1;
$myaddons[$maNum] = array('2229', '/uploads/allimg/200508/14021VY0-1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('2230', '/uploads/allimg/200508/14021U427-2.jpg');
$maNum = 3;
$myaddons[$maNum] = array('2231', '/uploads/allimg/200508/14021S536-3.jpg');
$maNum = 4;
$myaddons[$maNum] = array('2232', '/uploads/allimg/200508/14021U3W-4.jpg');
$maNum = 5;
