<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('806', '/uploads/allimg/200507/1R1261232-0.jpg');
$maNum = 1;
$myaddons[$maNum] = array('807', '/uploads/allimg/200507/1R12B100-1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('808', '/uploads/allimg/200507/1R1262a4-2.jpg');
$maNum = 3;
$myaddons[$maNum] = array('809', '/uploads/allimg/200507/1R12A253-3.jpg');
$maNum = 4;
$myaddons[$maNum] = array('810', '/uploads/allimg/200507/1R1264c6-4.jpg');
$maNum = 5;
$myaddons[$maNum] = array('811', '/uploads/allimg/200507/1R12Ca6-5.jpg');
$maNum = 6;
