<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('717', '/uploads/allimg/200507/1I919B18-0.jpg');
$maNum = 1;
$myaddons[$maNum] = array('718', '/uploads/allimg/200507/1I9192D3-1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('719', '/uploads/allimg/200507/1I9192418-2.jpg');
$maNum = 3;
$myaddons[$maNum] = array('720', '/uploads/allimg/200507/1I91924Z-3.jpg');
$maNum = 4;
$myaddons[$maNum] = array('721', '/uploads/allimg/200507/1I9193Y6-4.jpg');
$maNum = 5;
$myaddons[$maNum] = array('722', '/uploads/allimg/200507/1I9194559-5.jpg');
$maNum = 6;
