<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('3423', '/uploads/allimg/200508/2116394196-0.jpg');
$maNum = 1;
$myaddons[$maNum] = array('3424', '/uploads/allimg/200508/2116391527-1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('3425', '/uploads/allimg/200508/2116395M2-2.jpg');
$maNum = 3;
$myaddons[$maNum] = array('3426', '/uploads/allimg/200508/21163921N-3.jpg');
$maNum = 4;
$myaddons[$maNum] = array('3427', '/uploads/allimg/200508/2116394092-4.jpg');
$maNum = 5;
