<div class="readbox">
          <div class="readtitle"><a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]">[field:global.cfg_city/][field:title/]</a> </div>
          <div class="readimg"><a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]"><img src="[field:litpic/]" alt="[field:fulltitle/]" width="90" height="59"/></a> </div>
          <p>[field:info/]...</p>
        </div>