<li>
      <div class="viewimg [field:litpic runphp='yes'] $a='disno'; $b='dis'; if(@me=="/images/defaultpic.gif") @me=$a; else @me=$b; [/field:litpic]" >
      <div class="hotimgzz"></div>
      <a href="[field:arcurl/]" class="zzsz"></a>
      <a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]"><img src="[field:litpic/]" alt="[field:fulltitle/]" width="250" height="165"/></a>
      <!--//Í¼Æ¬ÉÏÏÔÊ¾À¸Ä¿<div class="standpoint">[field:typelink/]</div>-->
    </div>
    <h3><a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]">[field:shorttitle/]-[field:title/]</a>
    </h3>
    <p>[field:description/]</p>
    <span>[field:source/]</span><span>/</span><span><a href="[field:typeurl/]" target="_blank">[field:typename/]</a>
    </span><span>/</span><span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
    </li>