<?php
$z[0]=Array("field","",21,49);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("global","",122,145);
$z[1][4]=array();
$z[1][4]['name']="cfg_city";
$z[2]=Array("field","",145,174);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","<dd><a href=\"[field:typelink/]\" title=\"\" target=\"_self\">[field:typename/]</a></dd>",229,364);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>