<?php
$z[0]=Array("litpic"," \$a='disno'; \$b='dis'; if(@me==\"/images/defaultpic.gif\") @me=\$a; else @me=\$b; ",32,152);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",207,222);
$z[1][4]=array();
$z[2]=Array("arcurl","",266,281);
$z[2][4]=array();
$z[3]=Array("fulltitle","",307,325);
$z[3][4]=array();
$z[4]=Array("litpic","",345,360);
$z[4][4]=array();
$z[5]=Array("fulltitle","",367,385);
$z[5][4]=array();
$z[6]=Array("typelink","",457,474);
$z[6][4]=array();
$z[7]=Array("arcurl","",517,532);
$z[7][4]=array();
$z[8]=Array("fulltitle","",558,576);
$z[8][4]=array();
$z[9]=Array("title","",578,592);
$z[9][4]=array();
$z[10]=Array("description","",616,636);
$z[10][4]=array();
$z[11]=Array("pubdate","",655,706);
$z[11][4]=array();
$z[11][4]['function']="MyDate('Y-m-d H:i',@me)";

?>