<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",15,169);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",184,199);
$z[1][4]=array();
$z[2]=Array("title","",215,229);
$z[2][4]=array();
$z[3]=Array("pubdate","",286,332);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",360,374);
$z[4][4]=array();
$z[5]=Array("scores","",402,417);
$z[5][4]=array();
$z[6]=Array("description","",460,480);
$z[6][4]=array();

?>