<title>[field:array runphp=yes]
@me = (empty(@me['title']) ? "{@me['tag']}" : "{@me['title']}");
[/field:array]</title>
<meta name="keywords" content="[field:array runphp=yes]
@me = (empty(@me['keywords']) ? "泵业20余年来专业研究-{@me['tag']}，公司主要产品有：氟塑料磁力泵、氟塑料离心泵、{@me['tag']}、氟合金泵、防腐泵、四氟泵、耐腐蚀离心泵，专业技术工程师在线为您提供{@me['tag']}的选型报价
" : "{@me['keywords']}");
[/field:array]" />
<meta name="description" content="[field:array runphp=yes]
@me = (empty(@me['description']) ? "泵业20余年来专业研究-{@me['tag']}，公司主要产品有：氟塑料磁力泵、氟塑料离心泵、{@me['tag']}、氟合金泵、防腐泵、四氟泵、耐腐蚀离心泵，专业技术工程师在线为您提供{@me['tag']}的选型报价
" : "{@me['description']}");
[/field:array]" />