<?php
$z[0]=Array("array","\n@me = (empty(@me['title']) ? \"{@me['tag']}\" : \"{@me['title']}\");\n",7,111);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("array","\n@me = (empty(@me['keywords']) ? \"泵业20余年来专业研究-{@me['tag']}，公司主要产品有：氟塑料磁力泵、氟塑料离心泵、{@me['tag']}、氟合金泵、防腐泵、四氟泵、耐腐蚀离心泵，专业技术工程师在线为您提供{@me['tag']}的选型报价\n\" : \"{@me['keywords']}\");\n",151,431);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[2]=Array("array","\n@me = (empty(@me['description']) ? \"泵业20余年来专业研究-{@me['tag']}，公司主要产品有：氟塑料磁力泵、氟塑料离心泵、{@me['tag']}、氟合金泵、防腐泵、四氟泵、耐腐蚀离心泵，专业技术工程师在线为您提供{@me['tag']}的选型报价\n\" : \"{@me['description']}\");\n",470,756);
$z[2][4]=array();
$z[2][4]['runphp']="yes";

?>