
  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />
  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />
<m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />
<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />
<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />
<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />
<m:item name='投票模块' link='vote_main.php' rank='plus_投票模块' target='main' />
<m:item name='生成分站' link='fenzhan_makehtml.php' rank='plus_生成分站' target='main' />
<m:item name='自动提取缩略图' link='article_pic_main.php' rank='plus_自动提取缩略图' target='main' />
<m:item name='自定义TAG管理' link='diy_tags.php' rank='plus_自定义TAG管理' target='main' />
<m:item name='自定义副标题管理' link='fubiaoti.php' rank='plus_自定义副标题管理' target='main' />

