<li>
          <h3><a href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]">[field:title/]</a>
          </h3>
          <p><span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span></p>
          <div class="testimg"><img src="[field:litpic/]" alt="[field:fulltitle/]" /></div>
          <p>[field:description function= cn_substr('@me',130)/]</p>
          <a href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]" class="fulltext">+²é¿´ÏêÇé</a>
        </li>