<li>
            <div class="hotbox">
              <div class="hotimg">
                <div class="hotimgzz"></div>
                <img src="[field:litpic/]" alt="[field:fulltitle/]" width="250" height="165"/>
                <!--//Í¼Æ¬ÉÏÏÔÊ¾À¸Ä¿<div class="standpoint">[field:typename/]</div>-->
                <a class="zzsz" href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]"></a>
              </div>
              <h3><a href="[field:arcurl/]" title="[field:fulltitle/]" target="_blank">[field:title/]</a>
              </h3>
              <p>[field:info/]</p>
              <span>[field:source/]</span><span>/</span><span><a href="[field:typeurl/]" target="_blank">[field:typename/]</a>
              </span><span>/</span><span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
            </div>
          </li>