<?php
$z[0]=Array("global","@me=(@me+1)%2==0?\"\n        <li>\":\"\";",0,93);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("fulltitle","",147,165);
$z[1][4]=array();
$z[2]=Array("arcurl","",178,193);
$z[2][4]=array();
$z[3]=Array("title","",195,209);
$z[3][4]=array();
$z[4]=Array("global","@me=(@me+1)%2==0?\"\":\"</li>\n        \";",214,308);
$z[4][4]=array();
$z[4][4]['name']="autoindex";
$z[4][4]['runphp']="yes";

?>