<?php
$z[0]=Array("global","@me=(@me+1)%2==0?\"\r\n        <li>\":\"\";",0,94);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("fulltitle","",148,166);
$z[1][4]=array();
$z[2]=Array("arcurl","",179,194);
$z[2][4]=array();
$z[3]=Array("title","",196,210);
$z[3][4]=array();
$z[4]=Array("global","@me=(@me+1)%2==0?\"\":\"</li>\r\n        \";",226,321);
$z[4][4]=array();
$z[4][4]['name']="autoindex";
$z[4][4]['runphp']="yes";

?>