<?php
$z[0]=Array("title","",27,41);
$z[0][4]=array();
$z[1]=Array("fullurl","",63,79);
$z[1][4]=array();
$z[2]=Array("description","",113,159);
$z[2][4]=array();
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("stime","",190,204);
$z[3][4]=array();
$z[4]=Array("typename","",229,246);
$z[4][4]=array();
$z[5]=Array("writer","",270,285);
$z[5][4]=array();
$z[6]=Array("source","",309,324);
$z[6][4]=array();

?>