<?php
$z[0]=Array("litpic"," \$a='disno'; \$b='dis'; if(@me==\"/images/defaultpic.gif\") @me=\$a; else @me=\$b; ",31,151);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",204,219);
$z[1][4]=array();
$z[2]=Array("arcurl","",261,276);
$z[2][4]=array();
$z[3]=Array("fulltitle","",302,320);
$z[3][4]=array();
$z[4]=Array("litpic","",339,354);
$z[4][4]=array();
$z[5]=Array("fulltitle","",361,379);
$z[5][4]=array();
$z[6]=Array("typelink","",449,466);
$z[6][4]=array();
$z[7]=Array("arcurl","",506,521);
$z[7][4]=array();
$z[8]=Array("fulltitle","",547,565);
$z[8][4]=array();
$z[9]=Array("title","",567,581);
$z[9][4]=array();
$z[10]=Array("description","",603,623);
$z[10][4]=array();
$z[11]=Array("pubdate","",641,692);
$z[11][4]=array();
$z[11][4]['function']="MyDate('Y-m-d H:i',@me)";

?>