
-----------------------------------------------
<m:top name='模块管理' c='6,' display='block'>
    <m:item name='模块管理' link='module_main.php' rank='sys_module' target='main' />
    <m:item name='上传新模块' link='module_upload.php' rank='sys_module' target='main' />
    <m:item name='模块生成向导' link='module_make.php' rank='sys_module' target='main' />
    </m:top>
<m:top item='7' name='辅助插件' display='block'>
  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />
  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />
<m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />
<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />
<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />
<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />
<m:item name='投票模块' link='vote_main.php' rank='plus_投票模块' target='main' />
<m:item name='自动提取缩略图' link='article_pic_main.php' rank='plus_自动提取缩略图' target='main' />
<m:item name='自定义TAG管理' link='diy_tags.php' rank='plus_自定义TAG管理' target='main' />
<m:item name='自定义副标题管理' link='fubiaoti.php' rank='plus_自定义副标题管理' target='main' />
<m:item name='XML地图生成' link='map.php' rank='plus_starget='main' />

</m:top>



<m:top name='TAG高级管理插件' c='6,' display='block' rank=''>
<m:item name='TAG链接设置' link='taghtml/tags_config.php' rank='' target='main' />
<m:item name='TAG静态生成' link='taghtml/makehtml_tag.php' rank='' target='main' />
<m:item name='TAG高级管理' link='taghtml/tags_main.php' rank='' target='main' />
</m:top>


<p style='line-height:150%'><p style='line-height:150%'><p style='line-height:150%'>详细说明查看https://www.lol9.cn/dedecj/</p></p></p>
<m:top name='德得广告' display='block'>
<m:item name='德得模块' link='mda_main.php' rank='plus_广告管理' target='main'/>
<m:item name='广告管理' link='mda_main.php?dopost=place' rank='plus_广告管理' target='main'/>
<m:item name='查看报表' link='mda_main.php?dopost=report' rank='plus_广告管理' target='main'/>
<m:item name='结算中心' link='mda_main.php?dopost=account' rank='plus_广告管理' target='main'/>
<m:item name='德得设置' link='mda_main.php?dopost=setting' rank='plus_广告管理' target='main'/>
</m:top>






-----------------------------------------------
