<?php
$z[0]=Array("global","",89,115);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",118,144);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channelartlist","\r\n      <li><strong><a href=\"{dede:field name='typeurl'/}\" title=\"\" target=\"_self\"><span class=\"glyphicon \r\nglyphicon-book\"></span>{dede:field name='typename'/}</a>\r\n        </strong>\r\n        <dl>\r\n          <em></em>{dede:channel type='son' noself='yes'}<dd><a href=\"[field:typelink/]\" title=\"\" target=\"_self\">[field:typename/]</a></dd>{/dede:channel}\r\n        </dl>\r\n      </li>\r\n      ",324,769);
$z[2][4]=array();
$z[2][4]['typeid']="top";

?>