<?php
$z[0]=Array("global","",87,113);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",116,142);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channelartlist","\n      <li><strong><a href=\"{dede:field name='typeurl'/}\" title=\"\" target=\"_self\"><span class=\"glyphicon \nglyphicon-book\"></span>{dede:global.cfg_city/}{dede:field name='typename'/}</a>\n        </strong>\n        <dl>\n          <em></em>{dede:channel type='son' noself='yes'}<dd><a href=\"[field:typelink/]\" title=\"\" target=\"_self\">[field:typename/]</a></dd>{/dede:channel}\n        </dl>\n      </li>\n      ",317,777);
$z[2][4]=array();
$z[2][4]['typeid']="top";

?>