<?php
$z[0]=Array("global","",431,458);
$z[0][4]=array();
$z[0][4]['name']="cfg_seotitle";
$z[1]=Array("global","",502,532);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",569,596);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1590,1625);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",1855,1913);
$z[4][4]=array();
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("tag"," \r\n          <li><a href=\"[field:id function='mbp_tag_url(@me)'/]\" target=\"_blank\"><span style=\"font-size:1.[field:count/]em\">[field:tag /]</span></a></li>\r\n          ",1997,2208);
$z[5][4]=array();
$z[5][4]['row']="1200";
$z[5][4]['sort']="rand";
$z[6]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n          ",2434,2589);
$z[6][4]=array();
$z[6][4]['titlelen']="42";
$z[6][4]['typeid']="top";
$z[6][4]['orderby']="click";
$z[6][4]['row']="5";
$z[7]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n          ",2773,2898);
$z[7][4]=array();
$z[7][4]['titlelen']="42";
$z[7][4]['row']="5";
$z[8]=Array("include","",2963,3000);
$z[8][4]=array();
$z[8][4]['filename']="footer.htm";

?>