<?php
$z[0]=Array("global","",69,96);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","@me = date(\"Y-m-d\");",120,202);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmspath";
$z[1][4]['runphp']="yes";
$z[2]=Array("tag","\n    <url>\n        <loc>[field:global.cfg_basehost/][field:id function='mbp_tag_url(@me)'/]</loc>\n        <lastmod>[field:id runphp=yes]@me = date(\"Y-m-d\");[/field:id]</lastmod>\n        <changefreq>daily</changefreq>\n        <priority>0.8</priority>\n    </url>\n	",300,605);
$z[2][4]=array();
$z[2][4]['row']="6000";
$z[2][4]['sort']="new";

?>